2024-10-19 13:31:14,638 |WARNING  |неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\Евгений\PycharmProjects\pythonProject1\test_12_4.py", line 27, in test_run
    r2 = Runner(5)
         ^^^^^^^^^
  File "C:\Users\Евгений\PycharmProjects\pythonProject1\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
2024-10-19 13:31:14,639 |WARNING  |Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\Евгений\PycharmProjects\pythonProject1\test_12_4.py", line 15, in test_walk
    r1 = Runner("Вася",-5)
         ^^^^^^^^^^^^^^^^^
  File "C:\Users\Евгений\PycharmProjects\pythonProject1\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
